version: '3.9'

services:

    prestashop:
      image: prestashop/prestashop:1.7
      container_name: prestashop
      ports:
        - 8080:80
      networks:
        - prestashop

networks:
  prestashop: