version: '3.3'

services:

    prestashop:
      image: prestashop/prestashop:1.7
      container_name: prestashop_ssl
      ports:
        - 80:80
      networks:
        - prestashop

networks:
  prestashop: